# Generated by Django 5.0.14 on 2026-10-02 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Marca', models.CharField(max_length=100)),
                ('Modelo', models.CharField(max_length=100)),
                ('Año', models.IntegerField()),
                ('Color', models.CharField(max_length=50)),
                ('Precio', models.DecimalField(decimal_places=0, max_digits=20)),
                ('Kilometraje', models.IntegerField()),
                ('tipo_combustible', models.CharField(choices=[('gasolina', 'Gasolina'), ('diesel', 'Diesel'), ('electrico', 'Electrico'), ('hibrido', 'Hibrido')], max_length=50)),
                ('transmision', models.CharField(choices=[('manual', 'Manual'), ('automatica', 'Automatica')], max_length=50)),
                ('numero_de_puertas', models.IntegerField()),
                ('fecha_de_registro', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
