# Generated by Django 5.0.14 on 2026-10-07 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('año', models.IntegerField()),
                ('color', models.CharField(max_length=50)),
                ('precio', models.DecimalField(decimal_places=0, max_digits=20)),
                ('kilometraje', models.IntegerField()),
                ('tipo_combustible', models.CharField(choices=[('gasolina', 'Gasolina'), ('diesel', 'Diesel'), ('electrico', 'Electrico'), ('hibrido', 'Hibrido')], max_length=50)),
                ('transmision', models.CharField(choices=[('manual', 'Manual'), ('automatica', 'Automatica')], max_length=50)),
                ('numero_puertas', models.IntegerField()),
                ('fecha_registro', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
